COMMANDS = [
    "bật",
    'tắt',
    'sáng',
    'chạy',
    'dừng',
    'đóng',
    'ngắt',
    'mở',
]

OBJECTS = [
    'điện',
    'đèn',
    'đèn chiếu sáng',
    'đèn ngủ',
    'đèn sưởi',
    'đèn học',
    'đèn nháy',
    'đèn chùm',
    'đèn thờ',
    'quạt',
    'quạt trần',
    'quạt cây',
    'quạt máy',
    'quạt điện',
    'điều hòa',
    'tivi',
    'tủ lạnh',
    'lò vi sóng',
    'dàn âm thanh',
    'máy giặt',
    'máy rửa bát',
    'máy lạnh',
    'lò nướng',
    'bếp điện',
    'bếp từ',
    'rèm cửa',
    'máy vi tính',
]

LOCATIONS = [
    'bếp',
    'nhà bếp',
    'nhà tắm',
    'phòng tắm',
    'phòng bếp',
    'phòng khách',
    'phòng ngủ',
    'phòng học',
    'phòng ăn',
    'phòng thờ',
    'phòng vệ sinh',
    'phòng giải trí',
    'phòng làm việc',
    'nhà vệ sinh',
    'sân',
    'hành lang',
    'cầu thang',
    'sân thượng',
    'sân phơi',
    'khu giải trí',
    'cửa ra vào',
    'cửa sổ',
]